# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

# Индексирование и выборка в NumPy

В этой лекции мы увидим, как выбирать элементы или группы элементов в массиве.

In [1]:
import numpy as np

In [2]:
#Creating sample array
arr = np.arange(0,11)

In [3]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Индексы и срезы
Самый простой способ выбрать один или несколько элементов массива очень похож на списки Python:

In [4]:
#Get a value at an index
arr[8]

8

In [5]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [6]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

## Трансляция

Массивы NumPy отличаются от обычных списков Python своей способностью транслировать. Со списками вы можете переназначать только части списка новыми частями того же размера и формы. То есть, если вы хотите заменить первые 5 элементов в списке новым значением, вам придется передать новый список из 5 элементов. С массивами NumPy вы можете транслировать одно значение по большему набору значений:

In [7]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [8]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [10]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Обратите внимание, что изменения произошли и в нашем исходном массиве!

In [11]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Данные не копируются, это вид исходного массива! Это позволяет избежать проблем с памятью!

In [12]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Индексирование 2D-массива (матриц)

Общий формат: **arr_2d [строка] [столбец]** или **arr_2d [строка, столбец]**. Я рекомендую использовать запятую для ясности.

In [13]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [14]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [15]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [16]:
# Getting individual element value
arr_2d[1,0]

20

In [17]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [18]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [19]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

## Дополнительная справка по индексированию
Поначалу индексирование 2D-матрицы может немного сбивать с толку, особенно когда вы начинаете увеличивать размер шага. Попробуйте поискать изображения в Google *NumPy indexing*, чтобы найти полезные примеры, например вот это:

<img src= 'numpy_indexing.png' width=500/> Источник изображения: http://www.scipy-lectures.org/intro/numpy/numpy.html

## Условный выбор

Это очень фундаментальная концепция, которая позже будет напрямую переведена на pandas, убедитесь, что вы понимаете эту часть!

Давайте кратко рассмотрим, как использовать скобки для выбора на основе операторов сравнения.

In [20]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [22]:
bool_arr = arr>4

In [23]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [24]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [25]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])