#### 1. Импортировать NumPy как np

In [1]:
import numpy as np

#### 2. Создайте массив из 10 нулей.

In [2]:
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [2]:
# DON'T WRITE HERE

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. Создайте массив из 10 единиц

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [3]:
# DON'T WRITE HERE

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 4. Создайте массив из 10 пятерок.

In [4]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [4]:
# DON'T WRITE HERE

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### 5. Создайте массив целых чисел от 10 до 50.

In [6]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [5]:
# DON'T WRITE HERE

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### 6. Создайте массив всех четных целых чисел от 10 до 50.

In [10]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [6]:
# DON'T WRITE HERE

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### 7. Создайте матрицу 3x3 со значениями от 0 до 8.

In [29]:
np.arange(0, 9).reshape(3, 3) # np.array([np.arange(3), np.arange(3, 6), np.arange(6, 9)]) # np.arange(0, 8).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
# DON'T WRITE HERE

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 8. Создайте единичную матрицу 3x3.

In [15]:
np.identity(3)  #np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
# DON'T WRITE HERE

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 9. Используйте NumPy для генерации случайного числа от 0 до 1<br><br> ПРИМЕЧАНИЕ. Значение вашего результата должно отличаться от показанного ниже.

In [32]:
np.random.rand(1)

array([0.1960112])

In [9]:
# DON'T WRITE HERE

array([0.65248055])

#### 10. Используйте NumPy для создания массива из 25 случайных чисел, выбранных из стандартного нормального распределения. <br><br> ПРИМЕЧАНИЕ. Значения вашего результата должны отличаться от показанных ниже.

In [33]:
np.random.rand(25)

array([0.55459282, 0.93406818, 0.40691135, 0.06470889, 0.34311398,
       0.35732152, 0.70507087, 0.42661198, 0.57715455, 0.60389605,
       0.787503  , 0.7143959 , 0.33389015, 0.96486954, 0.20339715,
       0.54138187, 0.61860199, 0.22388578, 0.8990034 , 0.45146259,
       0.80165018, 0.95111145, 0.02051387, 0.75627082, 0.14728367])

In [21]:
# DON'T WRITE HERE

#### 11. Создайте следующую матрицу:

In [34]:
np.arange(1, 101).reshape(10, 10) / 100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [11]:
# DON'T WRITE HERE

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### 12. Создайте массив из 20 точек с линейным интервалом между 0 и 1:

In [35]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [12]:
# DON'T WRITE HERE

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Индексация и Выборка

Теперь вам будет предоставлена ​​начальная матрица (обязательно запустите ячейку ниже!), И вам будет предложено воспроизвести результирующие выходные данные матрицы:

In [46]:
# RUN THIS CELL - THIS IS OUR STARTING MATRIX
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 13. Напишите код, воспроизводящий вывод, показанный ниже. <br><br> Будьте осторожны, не запускайте ячейку непосредственно над выводом, иначе вы больше не сможете видеть вывод.

In [58]:
# mat = np.arange(1,26).reshape(5,5)
# mat[mat > 11]
mat[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [14]:
# DON'T WRITE HERE

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

#### 14. Напишите код, воспроизводящий результат, показанный ниже.

In [62]:
mat[3][4]

20

In [15]:
# DON'T WRITE HERE

20

#### 15. Напишите код, воспроизводящий результат, показанный ниже.

In [66]:
mat[:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

In [16]:
# DON'T WRITE HERE

array([[ 2],
       [ 7],
       [12]])

#### 16. Напишите код, воспроизводящий результат, показанный ниже.

In [64]:
mat[4]

array([21, 22, 23, 24, 25])

In [17]:
# DON'T WRITE HERE

array([21, 22, 23, 24, 25])

#### 17. Напишите код, воспроизводящий результат, показанный ниже.

In [67]:
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [18]:
# DON'T WRITE HERE

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## Операции NumPy

#### 18. Получите сумму всех значений в mat.

In [68]:
mat.sum()

325

In [19]:
# DON'T WRITE HERE

325

#### 19. Получите стандартное отклонение значений в mat.

In [70]:
mat.std()

7.211102550927978

In [20]:
# DON'T WRITE HERE

7.211102550927978

#### 20. Получите сумму всех столбцов в mat.

In [71]:
sum(mat)

array([55, 60, 65, 70, 75])

In [21]:
# DON'T WRITE HERE

array([55, 60, 65, 70, 75])

## Бонусный вопрос

Мы много работали со случайными данными с помощью numpy, но есть ли способ гарантировать, что мы всегда получаем одни и те же случайные числа? [Нажмите здесь, чтобы получить подсказку](https://www.google.com/search?q=numpy+random+seed&rlz=1C1CHBF_enUS747US747&oq=numpy+random+seed&aqs=chrome..69i57j69i60j0l4.2087j0j7&sourceid=Frome)

In [72]:
np.seed()

AttributeError: module 'numpy' has no attribute 'seed'

# Great Job!