# Основы тензорной системы
В этом разделе рассматриваются:
* Преобразование массивов NumPy в тензоры PyTorch 
* Создание тензоров с нуля

## Выполните стандартный импорт

In [1]:
import torch
import numpy as np

Убедитесь, что вы используете PyTorch версии 1.1.0.

In [2]:
torch.__version__

'1.1.0'

## Преобразование массивов NumPy в тензоры PyTorch
<a href='https://pytorch.org/docs/stable/tensors.html'><strong><tt>torch.Tensor</tt></strong></a> - это многомерная матрица, содержащая элементы одного типа данных. <br>
Вычисления между тензорами возможны только в том случае, если тензоры имеют один и тот же dtype.<br>
В некоторых случаях тензоры используются в качестве замены NumPy для использования мощности графических процессоров (подробнее об этом позже).

In [3]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)
print(type(arr))

[1 2 3 4 5]
int32
<class 'numpy.ndarray'>


In [4]:
x = torch.from_numpy(arr)
# Equivalent to x = torch.as_tensor(arr)

print(x)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)


In [5]:
# Print the type of data held by the tensor
print(x.dtype)

torch.int32


In [6]:
# Print the tensor object type
print(type(x))
print(x.type()) # this is more specific!

<class 'torch.Tensor'>
torch.IntTensor


In [7]:
arr2 = np.arange(0.,12.).reshape(4,3)
print(arr2)

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


In [8]:
x2 = torch.from_numpy(arr2)
print(x2)
print(x2.type())

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)
torch.DoubleTensor


Здесь <tt>torch.DoubleTensor</tt> относится к 64-битным данным с плавающей запятой.

<h2><a href='https://pytorch.org/docs/stable/tensors.html'>Tensor Datatypes</a></h2>
<table style="display: inline-block">
<tr><th>TYPE</th><th>NAME</th><th>EQUIVALENT</th><th>TENSOR TYPE</th></tr>
<tr><td>32-bit integer (signed)</td><td>torch.int32</td><td>torch.int</td><td>IntTensor</td></tr>
<tr><td>64-bit integer (signed)</td><td>torch.int64</td><td>torch.long</td><td>LongTensor</td></tr>
<tr><td>16-bit integer (signed)</td><td>torch.int16</td><td>torch.short</td><td>ShortTensor</td></tr>
<tr><td>32-bit floating point</td><td>torch.float32</td><td>torch.float</td><td>FloatTensor</td></tr>
<tr><td>64-bit floating point</td><td>torch.float64</td><td>torch.double</td><td>DoubleTensor</td></tr>
<tr><td>16-bit floating point</td><td>torch.float16</td><td>torch.half</td><td>HalfTensor</td></tr>
<tr><td>8-bit integer (signed)</td><td>torch.int8</td><td></td><td>CharTensor</td></tr>
<tr><td>8-bit integer (unsigned)</td><td>torch.uint8</td><td></td><td>ByteTensor</td></tr></table>

## Копирование или совместное использование

<a href='https://pytorch.org/docs/stable/torch.html#torch.from_numpy'><strong><tt>torch.from _numpy () </tt></strong></a><br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.as_tensor'><strong><tt>torch.as_ тензор () </tt></strong></a><br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.tensor'><strong><tt>torch.tensor () </tt></strong></a><br>

Существует ряд различных функций, доступных для <a href='https://pytorch.org/docs/stable/torch.html#creation-ops'>создания тензоров</a>. При использовании <a href='https://pytorch.org/docs/stable/torch.html#torch.from_numpy'><strong><tt>torch.from _numpy () </tt></strong></a> и <a href='https://pytorch.org/docs/stable/torch.html#torch.as_tensor'><strong><tt>torch.as_ tensor () </tt></strong></a>, исходный массив Numpy и тензор Numpy используют одну и ту же память. Это означает, что изменения одного влияют на другого. Однако функция <a href='https://pytorch.org/docs/stable/torch.html#torch.tensor'><strong><tt>torch.tensor () </tt></strong></a> всегда делает копию.

In [9]:
# Using torch.from_numpy()
arr = np.arange(0,5)
t = torch.from_numpy(arr)
print(t)

tensor([0, 1, 2, 3, 4], dtype=torch.int32)


In [10]:
arr[2]=77
print(t)

tensor([ 0,  1, 77,  3,  4], dtype=torch.int32)


In [11]:
# Using torch.tensor()
arr = np.arange(0,5)
t = torch.tensor(arr)
print(t)

tensor([0, 1, 2, 3, 4], dtype=torch.int32)


In [12]:
arr[2]=77
print(t)

tensor([0, 1, 2, 3, 4], dtype=torch.int32)


## Class constructors
<a href='https://pytorch.org/docs/stable/tensors.html'><strong><tt>torch.Tensor()</tt></strong></a><br>
<a href='https://pytorch.org/docs/stable/tensors.html'><strong><tt>torch.FloatTensor()</tt></strong></a><br>
<a href='https://pytorch.org/docs/stable/tensors.html'><strong><tt>torch.LongTensor()</tt></strong></a>, etc.<br>

There's a subtle difference between using the factory function <font color=black><tt>torch.tensor(data)</tt></font> and the class constructor <font color=black><tt>torch.Tensor(data)</tt></font>.<br>
The factory function determines the dtype from the incoming data, or from a passed-in dtype argument.<br>
The class constructor <tt>torch.Tensor()</tt>is simply an alias for <tt>torch.FloatTensor(data)</tt>. Consider the following:

## Конструкторы классов
<a href='https://pytorch.org/docs/stable/tensors.html'><strong><tt>torch.Tensor() </tt></strong></a><br>
<a href='https://pytorch.org/docs/stable/tensors.html'><strong><tt>torch.FloatTensor() </tt></strong></a><br>
<a href='https://pytorch.org/docs/stable/tensors.html'><strong><tt>torch.LongTensor() </tt></strong></a> и т. д. <br>

Есть небольшая разница между использованием фабричной функции <font color=black><tt>torch.tensor(data)</tt></font> и конструктора класса <font color=black><tt>torch.Tensor(data)</tt></font>.<br>
Заводская функция определяет dtype из входящих данных или из переданного аргумента dtype. <br>
Конструктор класса <tt>torch.Tensor()</tt> - это просто псевдоним для <tt>torch.FloatTensor(data)</tt>. Учтите следующее:

In [13]:
data = np.array([1,2,3])

In [14]:
a = torch.Tensor(data)  # Equivalent to cc = torch.FloatTensor(data)
print(a, a.type())

tensor([1., 2., 3.]) torch.FloatTensor


In [15]:
b = torch.tensor(data)
print(b, b.type())

tensor([1, 2, 3], dtype=torch.int32) torch.IntTensor


In [16]:
c = torch.tensor(data, dtype=torch.long)
print(c, c.type())

tensor([1, 2, 3]) torch.LongTensor


## Создание тензоров с нуля
### Неинициализированные тензоры с <tt>.empty () </tt>
<a href='https://pytorch.org/docs/stable/torch.html#torch.empty'><strong><tt>torch.empty()</tt></strong></a> возвращает <em>неинициализированный</em> тензор. По сути, блок памяти выделяется в соответствии с размером тензора, и возвращаются любые значения, уже находящиеся в блоке. Это похоже на поведение <tt>numpy.empty () </tt>.

In [17]:
x = torch.empty(4, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


### Инициализированные тензоры с <tt>.zeros () </tt> и <tt>.ones () </tt>
<a href='https://pytorch.org/docs/stable/torch.html#torch.zeros'><strong><tt>torch.zeros(размер) </tt></strong></a><br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.ones'><strong><tt>torch.ones(размер) </tt></strong></a><br>
Хорошая идея - передать предполагаемый dtype.

In [18]:
x = torch.zeros(4, 3, dtype=torch.int64)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


### Tensors from ranges
<a href='https://pytorch.org/docs/stable/torch.html#torch.arange'><strong><tt>torch.arange(start,end,step)</tt></strong></a><br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.linspace'><strong><tt>torch.linspace(start,end,steps)</tt></strong></a><br>
Note that with <tt>.arange()</tt>, <tt>end</tt> is exclusive, while with <tt>linspace()</tt>, <tt>end</tt> is inclusive.

### Тензоры из диапазонов
<a href='https://pytorch.org/docs/stable/torch.html#torch.arange'><strong><tt>torch.arange(начало, конец, шаг) </tt></strong></a><br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.linspace'><strong><tt>torch.linspace(начало, конец, шаги) </tt></strong></a><br>
Обратите внимание, что с <tt>.arange()</tt>, <tt>конец</tt> является эксклюзивным, в то время как с <tt>linspace()</tt>, <tt>конец</tt> является включенным.

In [19]:
x = torch.arange(0,18,2).reshape(3,3)
print(x)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])


In [20]:
x = torch.linspace(0,18,12).reshape(3,4)
print(x)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])


### Тензоры из данных
<tt>torch.tensor()</tt> подберет dtype на основе входящих данных:

In [21]:
x = torch.tensor([1, 2, 3, 4])
print(x)
print(x.dtype)
print(x.type())

tensor([1, 2, 3, 4])
torch.int64
torch.LongTensor


В качестве альтернативы вы можете установить тип с помощью используемого метода тензора.
Список типов тензоров можно найти на https://pytorch.org/docs/stable/tensors.html.

In [22]:
x = torch.FloatTensor([5,6,7])
print(x)
print(x.dtype)
print(x.type())

tensor([5., 6., 7.])
torch.float32
torch.FloatTensor


Вы также можете передать dtype в качестве аргумента. Чтобы просмотреть список типов dtypes, посетите https://pytorch.org/docs/stable/tensor_attributes.html#torch.torch.dtype<br>.

In [23]:
x = torch.tensor([8,9,-3], dtype=torch.int)
print(x)
print(x.dtype)
print(x.type())

tensor([ 8,  9, -3], dtype=torch.int32)
torch.int32
torch.IntTensor


### Changing the dtype of existing tensors
Don't be tempted to use <tt>x = torch.tensor(x, dtype=torch.type)</tt> as it will raise an error about improper use of tensor cloning.<br>
Instead, use the tensor <tt>.type()</tt> method.

### Изменение dtype существующих тензоров
Не поддавайтесь соблазну использовать <tt>x = torch.tensor (x, dtype = torch.type)</tt>, так как это даст ошибку о неправильном использовании тензорного клонирования.<br>.
Вместо этого используйте тензорный метод <tt>.type()</tt>.

In [24]:
print('Old:', x.type())

x = x.type(torch.int64)

print('New:', x.type())

Old: torch.IntTensor
New: torch.LongTensor


### Random number tensors
<a href='https://pytorch.org/docs/stable/torch.html#torch.rand'><strong><tt>torch.rand(size)</tt></strong></a> returns random samples from a uniform distribution over [0, 1)<br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.randn'><strong><tt>torch.randn(size)</tt></strong></a> returns samples from the "standard normal" distribution [σ = 1]<br>
&nbsp;&nbsp;&nbsp;&nbsp;Unlike <tt>rand</tt> which is uniform, values closer to zero are more likely to appear.<br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.randint'><strong><tt>torch.randint(low,high,size)</tt></strong></a> returns random integers from low (inclusive) to high (exclusive)

### Тензоры случайных чисел
<a href='https://pytorch.org/docs/stable/torch.html#torch.rand'><strong><tt>torch.rand(size)</tt></strong></a> возвращает случайные выборки из равномерного распределения по [0, 1) <br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.randn'><strong><tt>torch.randn(size)</tt></strong></a> возвращает образцы из "стандартного нормального" распределения [σ = 1] <br>
В отличие от <tt>rand</tt>, который является однородным, более вероятно появление значений, близких к нулю.
<br><a href='https://pytorch.org/docs/stable/torch.html#torch.randint'><strong><tt>torch.randint (low, high, size) </tt></strong></a> возвращает случайные целые числа от low (включительно) до high (исключительного)

In [25]:
x = torch.rand(4, 3)
print(x)

tensor([[0.0211, 0.2336, 0.6775],
        [0.4790, 0.5132, 0.9878],
        [0.7552, 0.0789, 0.1860],
        [0.6712, 0.1564, 0.3753]])


In [26]:
x = torch.randn(4, 3)
print(x)

tensor([[ 0.7164, -0.1538, -0.9980],
        [-1.8252,  1.1863, -0.1523],
        [ 1.4093, -0.0212, -1.5598],
        [ 0.1831, -0.6961,  1.3497]])


In [27]:
x = torch.randint(0, 5, (4, 3))
print(x)

tensor([[0, 3, 0],
        [1, 3, 4],
        [1, 2, 3],
        [4, 4, 3]])


### Random number tensors that follow the input size
<a href='https://pytorch.org/docs/stable/torch.html#torch.rand_like'><strong><tt>torch.rand_like(input)</tt></strong></a><br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.randn_like'><strong><tt>torch.randn_like(input)</tt></strong></a><br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.randint_like'><strong><tt>torch.randint_like(input,low,high)</tt></strong></a><br> these return random number tensors with the same size as <tt>input</tt>

### Тензоры случайных чисел, повторяющие размерность ввода
<a href='https://pytorch.org/docs/stable/torch.html#torch.rand_like'><strong><tt>torch.rand _как (ввод) </tt></strong></a><br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.randn_like'><strong><tt>torch.randn_ like (ввод) </tt></strong></a><br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.randint_like'><strong><tt>torch.randint_like (input, low, high) </tt></strong></a><br> они возвращают тензоры случайных чисел того же размера, что и <tt>input</tt>

In [28]:
x = torch.zeros(2,5)
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [29]:
x2 = torch.randn_like(x)
print(x2)

tensor([[-0.5442, -0.3149,  0.0922,  1.1829, -0.7873],
        [ 0.3143,  0.9465,  0.4534,  0.4623,  2.2044]])


The same syntax can be used with<br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.zeros_like'><strong><tt>torch.zeros_like(input)</tt></strong></a><br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.ones_like'><strong><tt>torch.ones_like(input)</tt></strong></a>

Тот же синтаксис можно использовать с <br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.zeros_like'><strong><tt>torch.zeros_like(ввод) </tt></strong></a><br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.ones_like'><strong><tt>torch.ones_like(ввод) </tt></strong></a>

In [30]:
x3 = torch.ones_like(x2)
print(x3)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


### Установка случайного начального числа
<a href='https://pytorch.org/docs/stable/torch.html#torch.manual_seed'><strong><tt>torch.manual_seed (int) </tt></strong></a> используется для получения воспроизводимых результатов

In [31]:
torch.manual_seed(42)
x = torch.rand(2, 3)
print(x)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [32]:
torch.manual_seed(42)
x = torch.rand(2, 3)
print(x)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


## Тензорные атрибуты
Помимо <tt>dtype</tt>, мы можем посмотреть другие атрибуты <a href='https://pytorch.org/docs/stable/tensor_attributes.html'>тензоров</a>, такие как <tt>shape</tt>, <tt>device</tt> и <tt>layout</tt>.

In [33]:
x.shape

torch.Size([2, 3])

In [34]:
x.size()  # equivalent to x.shape

torch.Size([2, 3])

In [35]:
x.device

device(type='cpu')

PyTorch поддерживает использование нескольких <a href='https://pytorch.org/docs/stable/tensor_attributes.html#torch-device'>устройств</a>, используя мощность одного или нескольких GPU в дополнение к CPU. Мы не будем рассматривать это здесь, но вы должны знать, что операции между тензорами могут происходить только для тензоров, установленных на одном устройстве.

In [36]:
x.layout

torch.strided

PyTorch имеет класс для хранения параметра <a href='https://pytorch.org/docs/stable/tensor_attributes.html#torch.torch.layout'>memory layout</a>. Настройка по умолчанию <a href='https://en.wikipedia.org/wiki/Stride_of_an_array'>strided</a> будет соответствовать нашим целям на протяжении всего курса.