# Tensor Operations
This section covers:
* Indexing and slicing
* Reshaping tensors (tensor views)
* Tensor arithmetic and basic operations
* Dot products
* Matrix multiplication
* Additional, more advanced operations

## Perform standard imports

# Тензорные операции
В этом разделе рассматриваются:
* Индексирование и разбиение 
* Тензорное ремоделирование (тензорные представления)
* Тензорная арифметика и базовые операции 
* Точечные произведения
* Умножение матриц 
* Более сложные дополнительные операции

## Выполните стандартный импорт

# Opérations tensorielles
Cette rubrique couvre :
*Indexation et découpage* Remodelage des tenseurs (vues tenseurs)
*Arithmétique tensorielle et opérations de base* Produits à points
*Multiplication matricielle* Opérations supplémentaires plus avancées

## Effectuer des importations standard

In [1]:
import torch
import numpy as np

## Индексирование и срезы
Извлечение определенных значений из тензора работает так же, как с массивами NumPy.
<img src='numpy_indexing.png' width="500" style="display: inline-block"><br><br>
Источник изображения: http://www.scipy-lectures.org/_images/numpy_indexing.png

In [2]:
x = torch.arange(6).reshape(3,2)
print(x)

tensor([[0, 1],
        [2, 3],
        [4, 5]])


In [3]:
# Grabbing the right hand column values
x[:,1]

tensor([1, 3, 5])

In [4]:
# Grabbing the right hand column as a (3,1) slice
x[:,1:]

tensor([[1],
        [3],
        [5]])

## Измените форму тензоров с помощью <tt>.view() </tt>
<a href='https://pytorch.org/docs/master/tensors.html#torch.Tensor.view'><strong><tt>view()</tt></strong></a> и <a href='https://pytorch.org/docs/master/torch.html#torch.reshape'><strong><tt>reshape()</tt></strong></a> по сути делают то же самое, возвращая измененный тензор без изменения исходного тензора.
Есть хорошее обсуждение различий <a href='https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch'>по ссылке</a>.

In [5]:
x = torch.arange(10)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [6]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [7]:
x.view(5,2)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [8]:
# x is unchanged
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### View отражет самые свежие данные

In [9]:
z = x.view(2,5)
x[0]=234
print(z)

tensor([[234,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]])


### Просмотры могут определять правильный размер
Передавая <tt>-1</tt>, PyTorch выведет правильное значение из заданного тензора.

In [10]:
x.view(2,-1)

tensor([[234,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

In [11]:
x.view(-1,5)

tensor([[234,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

### Копирование формы другого тензора с <tt>.view _as()</tt>
<a href='https://pytorch.org/docs/master/tensors.html#torch.Tensor.view_as'><strong><tt>view_ as(input)</tt></strong></a> работает только с тензорами, имеющими одинаковое количество элементов.

In [12]:
x.view_as(z)

tensor([[234,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

## Тензорная арифметика
Добавление тензоров может выполняться несколькими способами в зависимости от желаемого результата. <br>

Как простое выражение:

In [13]:
a = torch.tensor([1,2,3], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)
print(a + b)

tensor([5., 7., 9.])


С помощью методов в torch:

In [14]:
print(torch.add(a, b))

tensor([5., 7., 9.])


С выходным тензором, переданным в качестве аргумента:

In [15]:
result = torch.empty(3)
torch.add(a, b, out=result)  # equivalent to result=torch.add(a,b)
print(result)

tensor([5., 7., 9.])


Заменой тензора

In [16]:
a.add_(b)  # equivalent to a=torch.add(a,b)
print(a)

tensor([5., 7., 9.])


<div class="alert alert-info"><strong> ПРИМЕЧАНИЕ: </strong> Любая операция, перезаписывающая тензор , фиксируется постфиксом с подчеркиванием _.
    <br>В приведенном выше примере: <tt>a.add_(b)</tt> изменен <tt>a</tt>.</div>

### Basic Tensor Operations
<table style="display: inline-block">
<caption style="text-align: center"><strong>Arithmetic</strong></caption>
<tr><th>OPERATION</th><th>FUNCTION</th><th>DESCRIPTION</th></tr>
<tr><td>a + b</td><td>a.add(b)</td><td>element wise addition</td></tr>
<tr><td>a - b</td><td>a.sub(b)</td><td>subtraction</td></tr>
<tr><td>a * b</td><td>a.mul(b)</td><td>multiplication</td></tr>
<tr><td>a / b</td><td>a.div(b)</td><td>division</td></tr>
<tr><td>a % b</td><td>a.fmod(b)</td><td>modulo (remainder after division)</td></tr>
<tr><td>a<sup>b</sup></td><td>a.pow(b)</td><td>power</td></tr>
<tr><td>&nbsp;</td><td></td><td></td></tr>
</table>

<table style="display: inline-block">
<caption style="text-align: center"><strong>Monomial Operations</strong></caption>
<tr><th>OPERATION</th><th>FUNCTION</th><th>DESCRIPTION</th></tr>
<tr><td>|a|</td><td>torch.abs(a)</td><td>absolute value</td></tr>
<tr><td>1/a</td><td>torch.reciprocal(a)</td><td>reciprocal</td></tr>
<tr><td>$\sqrt{a}$</td><td>torch.sqrt(a)</td><td>square root</td></tr>
<tr><td>log(a)</td><td>torch.log(a)</td><td>natural log</td></tr>
<tr><td>e<sup>a</sup></td><td>torch.exp(a)</td><td>exponential</td></tr>
<tr><td>12.34  ==>  12.</td><td>torch.trunc(a)</td><td>truncated integer</td></tr>
<tr><td>12.34  ==>  0.34</td><td>torch.frac(a)</td><td>fractional component</td></tr>
</table>

<table style="display: inline-block">
<caption style="text-align: center"><strong>Trigonometry</strong></caption>
<tr><th>OPERATION</th><th>FUNCTION</th><th>DESCRIPTION</th></tr>
<tr><td>sin(a)</td><td>torch.sin(a)</td><td>sine</td></tr>
<tr><td>cos(a)</td><td>torch.sin(a)</td><td>cosine</td></tr>
<tr><td>tan(a)</td><td>torch.sin(a)</td><td>tangent</td></tr>
<tr><td>arcsin(a)</td><td>torch.asin(a)</td><td>arc sine</td></tr>
<tr><td>arccos(a)</td><td>torch.acos(a)</td><td>arc cosine</td></tr>
<tr><td>arctan(a)</td><td>torch.atan(a)</td><td>arc tangent</td></tr>
<tr><td>sinh(a)</td><td>torch.sinh(a)</td><td>hyperbolic sine</td></tr>
<tr><td>cosh(a)</td><td>torch.cosh(a)</td><td>hyperbolic cosine</td></tr>
<tr><td>tanh(a)</td><td>torch.tanh(a)</td><td>hyperbolic tangent</td></tr>
</table>

<table style="display: inline-block">
<caption style="text-align: center"><strong>Summary Statistics</strong></caption>
<tr><th>OPERATION</th><th>FUNCTION</th><th>DESCRIPTION</th></tr>
<tr><td>$\sum a$</td><td>torch.sum(a)</td><td>sum</td></tr>
<tr><td>$\bar a$</td><td>torch.mean(a)</td><td>mean</td></tr>
<tr><td>a<sub>max</sub></td><td>torch.max(a)</td><td>maximum</td></tr>
<tr><td>a<sub>min</sub></td><td>torch.min(a)</td><td>minimum</td></tr>
<tr><td colspan="3">torch.max(a,b) returns a tensor of size a<br>containing the element wise max between a and b</td></tr>
</table>

## Скалярные произведения
Если оба тензора являются векторами, точечное произведение задается как: <br>

$\begin{bmatrix} a & b & c \end{bmatrix} \;\cdot\; \begin{bmatrix} d & e & f \end{bmatrix} = ad + be + cf$

Если тензоры включают вектор-столбец, то скалярное произведение представляет собой сумму результата умноженных матриц. Например: <br>
$\begin{bmatrix} a & b & c \end{bmatrix} \;\cdot\; \begin{bmatrix} d \\ e \\ f \end{bmatrix} = ad + be + cf$<br><br>
Скалярные произведения могут быть выражены как <a href='https://pytorch.org/docs/stable/torch.html#torch.dot'><strong><tt>torch.dot (a, b) </tt></strong></a> или `a.dot (b)` или `b.dot (a)`

In [18]:
a = torch.tensor([1,2,3], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)
print(a.mul(b)) # for reference
print()
print(a.dot(b))

tensor([ 4., 10., 18.])

tensor(32.)


<div class="alert alert-info"><strong> ПРИМЕЧАНИЕ: </strong> Между <tt>torch.dot() </tt> и <tt>numpy.dot() </tt> есть небольшая разница. В то время как <tt>torch.dot() </tt> принимает только одномерные аргументы и возвращает скалярное произведение, <tt>numpy.dot() </tt> также принимает двухмерные аргументы и выполняет матричное умножение.

## Умножение матриц
2D <a href='https://en.wikipedia.org/wiki/Matrix_multiplication'>умножение матриц</a> возможно, когда количество столбцов в тензоре <strong><tt>A</tt></strong> совпадает с количеством строк в тензоре <strong><tt>B</tt></strong>. В этом случае произведение тензора <strong><tt>A</tt></strong> с размером $(x,y)$ и тензора <strong><tt>B</tt></strong> с размером $(y,z)$ дает тензор размера $(x,z)$
<div>
<div align="left"><img src='../Images/Matrix_multiplication_diagram.png' align="left"><br><br>

$\begin{bmatrix} a & b & c \\
d & e & f \end{bmatrix} \;\times\; \begin{bmatrix} m & n \\ p & q \\ r & s \end{bmatrix} = \begin{bmatrix} (am+bp+cr) & (an+bq+cs) \\
(dm+ep+fr) & (dn+eq+fs) \end{bmatrix}$</div></div>

<div style="clear:both">Источник изображения: <a href='https://commons.wikimedia.org/wiki/File:Matrix_multiplication_diagram_2.svg'>https: //commons.wikimedia.org/wiki/File: Matrix _multiplication_ diagram_2.svg</a></div>

Умножение матриц можно вычислить с помощью <a href='https://pytorch.org/docs/stable/torch.html#torch.mm'><strong><tt>torch.mm (a, b) </tt></strong></a> или `a.mm (b)` или `a @ b`

In [19]:
a = torch.tensor([[0,2,4],[1,3,5]], dtype=torch.float)
b = torch.tensor([[6,7],[8,9],[10,11]], dtype=torch.float)

print('a: ',a.size())
print('b: ',b.size())
print('a x b: ',torch.mm(a,b).size())

a:  torch.Size([2, 3])
b:  torch.Size([3, 2])
a x b:  torch.Size([2, 2])


In [20]:
print(torch.mm(a,b))

tensor([[56., 62.],
        [80., 89.]])


In [21]:
print(a.mm(b))

tensor([[56., 62.],
        [80., 89.]])


In [22]:
print(a @ b)

tensor([[56., 62.],
        [80., 89.]])


## Количество элементов
<a href='https://pytorch.org/docs/stable/torch.html#torch.numel'><strong><tt>torch.numel() </tt></strong></a>

Возвращает количество элементов в тензоре.

In [26]:
x = torch.ones(3,7)
x.numel()

21

Это может быть полезно в определенных вычислениях, таких как среднеквадратическая ошибка: <br>
<tt>
def mse(t1, t2):<br>
&nbsp;&nbsp;&nbsp;&nbsp;diff = t1 - t2<br>
    &nbsp;&nbsp;&nbsp;&nbsp;return torch.sum(diff * diff) / diff<strong>.numel()</strong></tt>